#Install nginx role
- src: https://github.com/jdauphant/ansible-role-nginx.git
  version: master
  name: nginx

#Install php-fpm role
- src: https://github.com/NBZ4live/ansible-php-fpm.git
  version: master
  name: php-fpm