
- hosts: all
  become: True
  roles:
    - { role: base, tags: ['base'] }

- hosts: database
  become: True
  roles:
    - { role: mysql, tags: ['mysql'] }

- hosts: appserver
  become: True
  roles:
 #   - { role: apache, tags: ['apache'] }
    - { role: php-fpm, tags: ['php-fpm'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: webapp, tags: ['webapp'] }



